from __future__ import annotations

import logging
import sys
from datetime import date
from pathlib import Path
import os

from .config import load_edge_config
from .pipeline import run_daily_pipeline


# test

logger = logging.getLogger(__name__)


DEFAULT_CONFIG_PATH = Path(
    "/opt/poultry-edge/config/edge.yml"
)


def configure_logging() -> None:
    """
    Configure the application logging.

    A common logging format and level are configured for the complete
    application so that messages generated by all modules follow the
    same structure.
    """

    logging.basicConfig(
        level=logging.INFO,
        format=(
            "%(asctime)s | %(levelname)s | "
            "%(name)s | %(message)s"
        ),
    )


def main() -> int:
    """
    Entry point of the edge application.

    Workflow:

    1. Configure application logging.
    2. Load and validate the configuration assigned to the edge.
    3. Read the MLflow connection settings from environment variables.
    4. Select the current date as the processing date.
    5. Run the complete daily Edge pipeline.

    Returns
    -------
    int
        Process exit code.

        A value of 0 indicates that the pipeline completed
        successfully. A value of 1 indicates that an exception
        occurred during execution.
    """

    # Initialize logging before loading the configuration so that any
    # subsequent error can be reported using the common application
    # format.
    configure_logging()

    try:
        # Load the farm-specific configuration mounted into the
        # container at the expected path.
        config = load_edge_config(
            config_path=DEFAULT_CONFIG_PATH,
        )

        logger.info(
            "Configuration loaded for farm '%s'.",
            config.farm.id,
        )

        # MLflow connection information is provided externally through
        # environment variables, keeping service-specific credentials
        # and endpoints outside the application image.
        tracking_uri = os.getenv(
            "MLFLOW_TRACKING_URI"
        )

        # If no dedicated registry URI is provided, use the same URI
        # configured for MLflow tracking.
        registry_uri = os.getenv(
            "MLFLOW_REGISTRY_URI",
            tracking_uri,
        )

        logger.info(
            "MLflow configuration. "
            "Tracking URI='%s', Registry URI='%s'.",
            tracking_uri,
            registry_uri,
        )

        # The daily pipeline processes the data associated with the
        # current local date of the Edge device.
        processing_date = date.today()

        # Execute the complete daily workflow, including model
        # synchronization, image discovery, inference and output
        # generation.
        run_daily_pipeline(
            config=config,
            processing_date=processing_date,
            tracking_uri=tracking_uri,
            registry_uri=registry_uri,
        )

    except Exception:
        # Any unhandled exception is logged together with its traceback
        # and converted into a non-zero process exit code.
        logger.exception(
            "The edge pipeline failed."
        )

        return 1

    logger.info(
        "Edge pipeline finished successfully."
    )

    return 0