name: Simulate Edge Deployment

on:
  workflow_dispatch:
    inputs:
      farm:
        description: Farm to deploy
        required: true
        default: farm_01
        type: choice
        options:
          - farm_01
          - farm_02

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show selected farm
        run: echo "Selected farm: ${{ inputs.farm }}"